version: "3.8"

services:
  log-generator:
    build: ./app
    volumes:
      - ./logs:/logs
    command: ["python", "log-generator.py"]

  fluentbit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./logs:/app/logs
    depends_on:
      - log-generator

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "24224:24224"
